name: adapters
description: Seguindo os princípios do Ports and Adapters - Alistair Cockburn essa lib é um agregado de todos os adaptadores utilizados por outros pacotes do projeto CodePlayData. Utilize apenas nos casos de aplicação descritos, pois estes estarão devidamente testados.
version: 0.5.3
homepage: https://github.com/codeplaydata

environment:
  sdk: ">=2.18.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
